#! /usr/local/bin/zsh
web="/usr/local/www/apache24/data/des17/Data/status.log";
echo "creating Pool $1...." > $web
if [[ $1 == "mirror" ]]; then
	zpool create Data mirror ada1 ada2 mirror ada3 ada4  2>txt/err.txt	
else
	zpool create Data $1 ada1 ada2 ada3 ada4 ada5 2>txt/err.txt
fi
err=`wc -c txt/err.txt | awk '{print $1}'`;
if [[ err -ge 3 ]]; then
	cat txt/err.txt > $web;
else
	echo pool Data of $1 is created. > $web;
fi 
