#! /usr/local/bin/zsh
web='/usr/local/www/apache24/data/des17/Data/status.log';
rm txt/err; 
domain=`echo $@ | awk '{ print $1 }' `;
domcapital=`echo $domain | tr '[:lower:]' '[:upper:]'`;
domsmall=`echo $domain | tr '[:upper:]' '[:lower:]'`;
dom=` echo $domsmall | awk -F. { print $1 }'`;
domaincont=`echo $@ | awk '{ print $4 }'`; 
admin=`echo $@ | awk '{ print $2 }'`;
pass=`echo $@ | awk '{ print $3 }'`;
echo changing Domain to $domain.... > $web;
echo $pass > txt/pass;
sed -e "s/DOMAIN/$dom/g" -e "s/DOMCOMP/$domcapital/g" -e "s/DOMSMALL/$domsmall/g" smb.confdomain > txt/smb.conf
sed 
err=`wc -c  txt/err.txt | awk '{print $1}'`;
if [[ $err >  4  ]]; then
	cat txt/err.txt > $web;
else 
 echo DONE...user $username is added > $web; 
fi;
