#! /usr/local/bin/zsh
cd /TopStor/;
websnaps='/usr/local/www/apache24/data/des17/Data/Hourlylist.txt';
list1=`crontab -l | awk -F"now" '{print $2}' | grep hourly`; 
list2=`echo $list1 | awk '{print $1"@"$2" "$2" "}'`;  
echo $list2
nameforjson=`echo $list2 | tr -d '\n'` ;
echo $nameforjson
jsonname=`./jsonthis2.sh $nameforjson`;
echo $jsonname > $websnaps 2>txt/err.txt

