#!/bin/sh

. /etc/rc.subr

name="QuickStor2"
start_cmd="${name}_start"
stop_cmd="${name}_stop"
rcvar=TopStor_enable
command="/TopStor/Quickstor2.sh"
command_interpreter="/usr/local/bin/zsh"
load_rc_config $name
: ${QuickStor_enable:=no}
: ${TopStor_msg="Nothing started."}
QuickStor2_start()
{
	echo "$TopStor_msg"
	/TopStor/Quickstor2.sh &
}
QuickStor2_stop()
{
	echo " it is stopped thanking God"
	pkill -HUP -f Quickstor2
}

run_rc_command "$1"
