#! /usr/local/bin/zsh
web='/usr/local/www/apache24/data/des17/Data/status.log';
rm txt/err.txt
echo Creating  snapshot.... > $web;
name=`echo $@ | awk '{print $1}'`;
DG=`echo $@ | awk '{print $2}'`;
FileS=` echo $@ | awk '{print $3}'`;
crontab -l > txt/cronthis.txt
/TopStor/SnapshotnowOnce $DG/$FileS $name. 2> txt/err.txt 
err=`wc -c  txt/err.txt | awk '{print $1}'`;
if [[ $err >  4  ]]; then
	cat txt/err.txt > $web;
else 
 echo DONE...Snapshot $DG/$FileS$name.$now1 is added > $web; 
fi;
./GetSnaplist

