#! /usr/local/bin/zsh
cd /TopStor
web='/usr/local/www/apache24/data/des17/Data/statusglobal.log';
rm txt/err.txt;
rm txt/cronthis.txt;
crontab -l > txt/cronthis.txt;
echo 1.$1 . 2.$2 . 3.$3 . 4.$4 . 5.$5 . 6.$6 . 7.$7 . 8.$8 . 9.$9 . 10.$10  > tmp;
cat txt/cronthis.txt | grep -v $@ > txt/cronthis.txt
crontab txt/cronthis.txt 2>txt/err.txt;
err=`wc -c  txt/err.txt | awk '{print $1}'`;
if [[ $err >  4  ]]; then
	cat txt/err.txt > $web;
else 
 echo DONE...Snapshot hourly.$day.$hr.$min is added > $web; 
fi;
