#! /usr/local/bin/zsh
cd /TopStor
web='/usr/local/www/apache24/data/des17/Data/statusglobal.log';
echo creating Snapshot $@.... > $web;
oper=$@; 
oper1=`echo $oper | awk '{print $1}'`;
oper2=`echo $oper | awk '{print $2}'`;
stamp=`date +%s`;
newsnap2=`echo $oper2.$stamp`;
newsnap=`echo $oper1@$newsnap2`;
/sbin/zfs snapshot $newsnap 2>> txt/err.txt
err=`wc -c  txt/err.txt | awk '{print $1}'`;
if [[ $err >  4  ]]; then
	cat txt/err.txt >> $web;
else 
timenow=`date`
echo $timenow: DONE...Snapshot $newsnap is created >> $web; 
fi;
sleep 2;
./GetSnaplist
