#! /usr/local/bin/zsh
web='/usr/local/www/apache24/data/des17/Data/status.log';
rm txt/err.txt
rm txt/cronthis.txt
echo Adding snapshot schedule.... > $web;
min=` echo $1 | awk '{print $2}'| awk -F: '{print $2}'`;
hr=`echo $1 | awk '{print $2}' | awk -F: '{print $1}'`;
day=`echo $1 | awk '{print $1}' | awk -F/ '{print $3}'`
month=`echo $1 | awk '{print $1}' | awk -F/ '{print $2}'`;
every=`echo $1 | awk '{print $3}'` ;
keep=`echo $1 | awk '{print $4}'`
DG=` echo $1 | awk '{print $5}'`; 
FileS=` echo $1 | awk '{print $6}'`;
crontab -l > txt/cronthis.txt
echo $min $hr $day $month "*" /TopStor/Snapshotcron $min  "'*'"/$every "'*'" "'*'" "'*'"  /TopStor/Snapshotnow $DG/$FileS hourly.$day.$hr.$min $keep 2> txt/err.txt >> txt/cronthis.txt
crontab txt/cronthis.txt 2>>txt/err.txt
err=`wc -c  txt/err.txt | awk '{print $1}'`;
if [[ $err >  4  ]]; then
	cat txt/err.txt > $web;
else 
 echo DONE...Snapshot hourly.$day.$hr.$min is added > $web; 
fi;
sleep 2
./GetPoolHourlylist
