#! /usr/local/bin/zsh
web='/usr/local/www/apache24/data/des17/Data/status.log';
rm txt/err.txt
rm txt/cronthis.txt
echo Adding snapshot schedule.... > $web;
stime=`echo $@ | awk '{print $1}'`;
hr=`echo $stime | awk -F: '{print $1}'`;
min=`echo $stime | awk -F: '{print $2}'`;
every=`echo $@ | awk '{print $2}'` ;
k=0; keep=`echo $@ | awk '{print $3}'`; keep=$(($keep+$k)); if (($keep < 1)); then keep=1; fi
DG=` echo $@ | awk '{print $4}'`; 
FileS=` echo $@ | awk '{print $5}'`;
crontab -l > txt/cronthis.txt
echo $min  $hr "*" "*" $every  /TopStor/Snapshotnow $DG/$FileS Weekly.$hr.$min.$every.$keep 2> txt/err.txt >> txt/cronthis.txt
crontab txt/cronthis.txt 2>>txt/err.txt
err=`wc -c  txt/err.txt | awk '{print $1}'`;
if [[ $err >  4  ]]; then
	cat txt/err.txt > $web;
else 
 echo DONE...Snapshot Weekly.$hr.$min.$every.$keep is added > $web; 
fi;
sleep 2
./GetPoolWeeklylist
