#!/bin/sh

. /etc/rc.subr

name="TopStor"
start_cmd="${name}_start"
stop_cmd="${name}_stop"
rcvar=TopStor_enable
command = "/TopStor/Topstor.sh"
load_rc_config $name
: ${TopStor_enable:=no}
: ${TopStor_msg="Nothing started."}
TopStor_start()
{
	echo "$TopStor_msg"
}
TopStor_stop()
{
	echo " it is already stopped."
}

run_rc_command "$1"
