#!/bin/sh

. /etc/rc.subr

name="TopStor"
start_cmd="${name}_start"
stop_cmd="${name}_stop"
rcvar=TopStor_enable
command="/TopStor/Topstor.sh"
command_interpreter="/usr/local/bin/zsh"
load_rc_config $name
: ${TopStor_enable:=no}
: ${TopStor_msg="TopStor started successfuly."}
TopStor_start()
{
	echo "$TopStor_msg"
	/TopStor/Topstor.sh &
}
TopStor_stop()
{
	echo " it is stopped thanking God"
	pkill -HUP -f Topstor
	touch /TopStor/txt/flag
}

run_rc_command "$1"
