#! /usr/local/bin/zsh
web='/usr/local/www/apache24/data/des17/Data/status.log';
rm txt/err; 
echo Adding user.... > $web;
username=`echo $1 | awk '{print $1}'`;
userpass=`echo $1 | awk '{print $2}'`;
( echo $userpass | pw add user $username -h 0 ) 2> txt/err.txt;
err=`wc -c  txt/err.txt | awk '{print $1}'`;
if [[ $err >  2  ]]; then
	cat txt/err.txt > $web;
else 
 echo DONE...user $username is added > $web; 
fi;
./UnixListUsers;
