#!/usr/local/bin/zsh
web="/usr/local/www/apache24/data/des17/Data/status.log";
username=$1;
echo Deleting user $username...> $web;
/usr/local/bin/smbpasswd -d $username;
pw user del $username -r  2>txt/err.txt;
echo DONE..user $username is deleted > $web;
err=`wc -c txt/err.txt | awk '{print $1}'`;
if [[ $err -ge 3 ]]; then
	cat txt/err.txt > $web;
fi;


